### ISSUE TITLE
Build is not working specially the 'tsc'...

### ISSUE THREAD

**Issue by ayan759619** [sjoerdvanBommel/youtube#3]
Trying to build the project , by npm run build as the option is provided in the package.json
tried, netlify, vercel.....
Still not working

**Comment by sjoerdvanBommel** [comment]
Hi @ayan759619 , for which branch did it not work? Thanks for pointing this out! :)

**Comment by ayan759619** [comment]
Hello, @sjoerdvanBommel 
https://github.com/sjoerdvanBommel/threeveloper/tree/020-folio-adding-materialized-objects-pt-2
This one .. as in your last video update regarding folio-2019

**Comment by sjoerdvanBommel** [comment]
@ayan759619  I pushed [a commit](https://github.com/sjoerdvanBommel/threeveloper/commit/8f1af6079e141204af81539bd6c3cba1a85bb4e6) to the branch, it should be resolved now, excuse me for the inconvenience :)
The issue was that the TypeScript compiler was checking the `node_modules` folder as well. It will now be skipped because I set `skipLibCheck` to `true`. Please let me know if this resolved your issue.

**Comment by ayan759619** [comment]
@sjoerdvanBommel  now no problem on build ... but
after deployment page is blank and on console its saying context lost... i even tried hostinh from ur branch by cloning ...
![Screenshot (53)](https://github.com/sjoerdvanBommel/threeveloper/assets/83729100/6688441d-76f8-49ab-a616-ba41c4e65a68)
i also tried serve -s dist 
but same problem persists...
